version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: alex
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
      MYSQL_DATABASE: setcourse
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - setcourse

  backend:
    restart: always
    build: 
      context: './backend'
    networks:
      - setcourse
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  frontend:
    restart: always
    build: 
      context: './frontend'
    ports:
      - "3000:3000"
    networks:
      - setcourse

networks:
  setcourse:
    driver: bridge
