# error constants
SUCCESS = 0
NO_SCHEDULE_OR_CLASS = 1
CLASS_EXISTS = 2
TIME_CONFLICT = 3
NOT_ENOUGH_UNITS = 4
NO_CLASSES_FOR_THIS_SCHEDULE = 5
NO_COURSE = 6
NO_CLASS = 7
NO_SCHEDULE = 8
NO_PROFESSOR = 9

# other constants
MAX_UNITS = 20